name: Code Formatting

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    prettier:
        name: Code Formatting
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            # Dependency Install ( package larni install qilish uchun )
            - name: Install dependencies
              run: npm install --legacy-peer-deps

            # Prettier ( kodlarni formatlash uchun )
            - name: Run Prettier check
              run: npx prettier --check . --ignore-path .prettierignore

            # ESLint ( kod xatoliklarni tekshiradi )
            - name: Run ESLint
              run: npx eslint . --ext .ts,.js,.tsx,.jsx

            # Unit Tests ( avtomatik test )
            # - name: Run Tests
            #   run: npx vitest run

            # Build Check ( loyiha build bo'ladimi )
            - name: Build
              run: npm run build

            # Dependency Check ( zaif va yaroqsiz kutubxonalarni packagelarni topadi )
            # - name: Audit dependencies
            #   run: npm audit --audit-level=high
